.TH "about" 3 "Thu Jul 16 2015" "DRNG Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
about \- About 
This is the DRNG Library, a project designed to bring the rdrand and rdseed instructions to customers who would traditionally not have access to them\&.
.PP
The 'rdrand' and 'rdseed' instructions are available at all privilege levels to any programmer, but tool chain support on some platforms is limited\&. One goal of this project is to provide access to these instructions via pre-compiled, static libraries\&. A second level goal is to provide a consistent, small, and very easy-to-use API to access the 'rdrand' and 'rdseed' instruction for various sizes of random data\&.
.PP
The source code and build system are provided for the entire library allowing the user to make any needed changes, or build dynamic versions, for incorporation into their own code\&.
.PP
Copyright(C) 2015 Intel Corporation\&. All rights reserved\&. 
