.TH "building" 3 "Thu Jul 16 2015" "DRNG Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
building \- Building 
Building the Rdrand Library is supported under Microsoft* Visual Studio 2013*, Linux* and OS X*\&. Use of the Intel(r) C++ Compiler is optional unless you are using a version of Visual Studio earlier than 2013 on Microsoft Windows*\&.
.PP
To build the library, open the rdrand Microsoft Visual Studio solution (rdrand\&.sln), and build the project as normal from the build menu\&. Included are two projects, rdrand the actual library and test, the demonstration program\&.
.PP
On Linux and OS X the build is wrapped with GNU* autoconf*\&. To build:
.PP
.PP
.nf
% \&./configure
% make
.fi
.PP
.PP
Copyright(C) 2015 Intel Corporation\&. All rights reserved\&.
.PP
\fC*\fP Other names and brands may be claimed as the property of others 
