.TH "doc.h" 3 "Thu Jul 16 2015" "DRNG Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doc.h \- Doxygen documentation source file\&. Move along\&. Nothing to see here\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Doxygen documentation source file\&. Move along\&. Nothing to see here\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for DRNG Library from the source code\&.
