.TH "legal_notice" 3 "Thu Jul 16 2015" "DRNG Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
legal_notice \- Legal Notice 
INFORMATION IN THIS DOCUMENT IS PROVIDED IN CONNECTION WITH INTEL PRODUCTS\&. NO LICENSE, EXPRESS OR IMPLIED, BY ESTOPPEL OR OTHERWISE, TO ANY INTELLECTUAL PROPERTY RIGHTS IS GRANTED BY THIS DOCUMENT\&. EXCEPT AS PROVIDED IN INTEL'S TERMS AND CONDITIONS OF SALE FOR SUCH PRODUCTS, INTEL ASSUMES NO LIABILITY WHATSOEVER AND INTEL DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTY, RELATING TO SALE AND/OR USE OF INTEL PRODUCTS INCLUDING LIABILITY OR WARRANTIES RELATING TO FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, OR INFRINGEMENT OF ANY PATENT, COPYRIGHT OR OTHER INTELLECTUAL PROPERTY RIGHT\&.
.PP
A 'Mission Critical Application' is any application in which failure of the Intel Product could result, directly or indirectly, in personal injury or death\&. SHOULD YOU PURCHASE OR USE INTEL'S PRODUCTS FOR ANY SUCH MISSION CRITICAL APPLICATION, YOU SHALL INDEMNIFY AND HOLD INTEL AND ITS SUBSIDIARIES, SUBCONTRACTORS AND AFFILIATES, AND THE DIRECTORS, OFFICERS, AND EMPLOYEES OF EACH, HARMLESS AGAINST ALL CLAIMS COSTS, DAMAGES, AND EXPENSES AND REASONABLE ATTORNEYS' FEES ARISING OUT OF, DIRECTLY OR INDIRECTLY, ANY CLAIM OF PRODUCT LIABILITY, PERSONAL INJURY, OR DEATH ARISING IN ANY WAY OUT OF SUCH MISSION CRITICAL APPLICATION, WHETHER OR NOT INTEL OR ITS SUBCONTRACTOR WAS NEGLIGENT IN THE DESIGN, MANUFACTURE, OR WARNING OF THE INTEL PRODUCT OR ANY OF ITS PARTS\&.
.PP
Intel may make changes to specifications and product descriptions at any time, without notice\&. Designers must not rely on the absence or characteristics of any features or instructions marked 'reserved' or 'undefined'\&. Intel reserves these for future definition and shall have no responsibility whatsoever for conflicts or incompatibilities arising from future changes to them\&. The information here is subject to change without notice\&. Do not finalize a design with this information\&.
.PP
The products described in this document may contain design defects or errors known as errata which may cause the product to deviate from published specifications\&. Current characterized errata are available on request\&.
.PP
Contact your local Intel sales office or your distributor to obtain the latest specifications and before placing your product order\&.
.PP
Copies of documents which have an order number and are referenced in this document, or other Intel literature, may be obtained by calling 1-800-548-4725, or go to: http://www.intel.com/design/literature.htm
.PP
.SS "Optimization Notice "
.PP
Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors\&. These optimizations include SSE2, SSE3, and SSE3 instruction sets and other optimizations\&. Intel does not guarantee the availability, functionality, or effectiveness of any optimization on microprocessors not manufactured by Intel\&.
.PP
Microprocessor-dependent optimizations in this product are intended for use with Intel microprocessors\&. Certain optimizations not specific to Intel microarchitecture are reserved for Intel microprocessors\&. Please refer to the applicable product User and Reference Guides for more information regarding the specific instruction sets covered by this notice\&.
.PP
Notice revision #20110804
.PP
Copyright(C) 2015 Intel Corporation\&. All rights reserved\&. 
